#!/bin/python3

import math
import os
import random
import re
import sys



def pageCount(n, p):
    
    if(p%2==0):
        a=p
    else:
        a=p-1
    a=a//2       
    return (min(a,(n//2)-a))
    # Write your code here

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    p = int(input().strip())

    result = pageCount(n, p)

    fptr.write(str(result) + '\n')

    fptr.close()
